// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqikkzbgvdjdrodroiqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxaWtremJndmRqZHJvZHJvaXFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxODAwOTMsImV4cCI6MjA2Mzc1NjA5M30.EN95NfbnGZ_11_6s5Y6j1Q7hNU8YndLjWWY0IbFblJk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);